# src/ingest/common.jl
#
# Shared helpers for ingest adapters. Loaded once from QuantumHardware.jl
# as the submodule QuantumHardware.IngestCommon — script-level ingest modules
# do `using QuantumHardware.IngestCommon` rather than re-including this file.

module IngestCommon

using SHA

export is_hand_curated, auto_generated_marker, snapshot_file

"""
Every ingest adapter writes this string as a top-of-file comment. Presence of
this marker in the first 20 lines of a device TOML means the adapter owns the
file and is allowed to overwrite it.
"""
const AUTO_MARKER_RE = r"#\s*Auto-generated by scripts/"

"""
    is_hand_curated(path) -> Bool

Return `true` if the TOML at `path` looks hand-curated — i.e. it does NOT carry
the `# Auto-generated by scripts/…` marker in its first 20 lines.

Ingest adapters MUST call this before overwriting any existing file. A `true`
return means "skip this file; a human or a different adapter owns it." The
rule is intentionally coarse: false positives (skipping a file we could safely
regenerate) are free; false negatives (clobbering real curation) cost data.

A second signal, `[meta] curation = "hand"`, can be set explicitly by a
curator to lock a file even if the auto-marker ever drifts.
"""
function is_hand_curated(path::AbstractString)
    isfile(path) || return false
    open(path, "r") do io
        # First scan the header comments.
        for _ in 1:20
            eof(io) && break
            line = readline(io)
            occursin(AUTO_MARKER_RE, line) && return false
            # Stop scanning once we reach the data body.
            startswith(strip(line), "[") && break
        end
        return true
    end
end

"""
    auto_generated_marker(script_name) -> String

Return the canonical marker line every ingest adapter should write at the
top of a generated TOML.
"""
auto_generated_marker(script_name::AbstractString) =
    "# Auto-generated by scripts/$(script_name). Hand-edits will be overwritten."

"""
    snapshot_file(src, repo_root, dest_dir, dest_name) -> (rel_path, sha256)

Copy `src` into `dest_dir/dest_name`, return the relative path (from
`repo_root`) and sha256 of the destination file. Used by every ingest adapter
to land a raw source under `sources/YYYY/MM/DD/…` per CLAUDE.md §4.
"""
function snapshot_file(src::AbstractString, repo_root::AbstractString,
                       dest_dir::AbstractString, dest_name::AbstractString)
    mkpath(dest_dir)
    dest = joinpath(dest_dir, dest_name)
    cp(src, dest; force=true)
    sha = bytes2hex(open(sha256, dest))
    rel = relpath(dest, repo_root)
    return rel, sha
end

end # module
