#!/usr/bin/env julia
# scripts/replay_ingest.jl
#
# Re-run each ingest adapter against the most recent cached raw source under
# `sources/`, then structurally diff the would-emit TOMLs against the committed
# devices/ TOMLs. Timestamps (created_at / updated_at / retrieved_at) are
# normalised out — they vary per replay-time and aren't substantive.
#
# Catches:
#   - ingest-adapter logic drift since the canonical run
#   - cached-raw corruption (sha256 changed → adapter reads different bytes)
#
# Hand-curated TOMLs (header lacks `# Auto-generated by scripts/`) are skipped:
# the adapter doesn't own them, so byte-level drift is expected.
#
# Exit 0 if no drift; 1 otherwise.

using Pkg
Pkg.activate(dirname(@__DIR__))

using TOML
using Dates
using QuantumHardware
using QuantumHardware.IngestCommon: is_hand_curated

const REPO_ROOT = dirname(@__DIR__)

include(joinpath(REPO_ROOT, "src", "ingest", "braket.jl"))
include(joinpath(REPO_ROOT, "src", "ingest", "quantinuum.jl"))

# --- Diff helpers -----------------------------------------------------------

const _IGNORE_KEYS = Set(["created_at", "updated_at", "retrieved_at"])

_normalize(x::AbstractDict) = Dict{String, Any}(
    k => _normalize(v) for (k, v) in x if !(k in _IGNORE_KEYS))
_normalize(x::AbstractVector) = [_normalize(e) for e in x]
_normalize(x) = x

structural_eq(a::AbstractDict, b::AbstractDict) = _normalize(a) == _normalize(b)

# --- Latest-snapshot lookup -------------------------------------------------

function _latest_snapshot(filename::AbstractString)
    sources_root = joinpath(REPO_ROOT, "sources")
    best_path = nothing
    best_date = nothing
    for (dir, _, files) in walkdir(sources_root)
        filename in files || continue
        parts = splitpath(dir)
        length(parts) >= 3 || continue
        try
            d = Date(parse(Int, parts[end-2]), parse(Int, parts[end-1]), parse(Int, parts[end]))
            if best_date === nothing || d > best_date
                best_date = d
                best_path = joinpath(dir, filename)
            end
        catch
            continue
        end
    end
    best_path === nothing && error("no `$filename` found under sources/YYYY/MM/DD/")
    return best_path, best_date
end

# --- Per-adapter replays ----------------------------------------------------

function setup_temp(temp_root::AbstractString)
    # Copy sources/ (a few MB) so adapters that snapshot files don't pollute
    # the real archive.
    cp(joinpath(REPO_ROOT, "sources"), joinpath(temp_root, "sources"))
    mkpath(joinpath(temp_root, "devices"))
end

function replay_braket(temp_root::AbstractString)
    docs_real, snap_date = _latest_snapshot("aws-braket-devices.html")
    rel = relpath(docs_real, REPO_ROOT)
    docs_in_temp = joinpath(temp_root, rel)
    @info "BraketIngest replay" snap_date docs=docs_in_temp
    BraketIngest.ingest(; repo_root=temp_root, today_date=snap_date, docs_html=docs_in_temp)
end

function replay_quantinuum(temp_root::AbstractString)
    cache = joinpath(REPO_ROOT, ".ingest-cache", "quantinuum-hw-specs")
    isdir(cache) || (@info "Quantinuum replay skipped — no .ingest-cache/" ; return false)
    _, snap_date = _latest_snapshot("quantinuum-spec-sheet-parameters.csv")
    @info "QuantinuumIngest replay" snap_date cache=cache
    QuantinuumIngest.ingest(; repo_root=temp_root, cache=cache, today_date=snap_date)
    return true
end

# --- Comparison -------------------------------------------------------------

function compare_devices(temp_root::AbstractString)
    devices_temp = joinpath(temp_root, "devices")
    devices_real = joinpath(REPO_ROOT, "devices")
    fails = 0
    n_compared = 0
    n_skipped = 0
    for (dir, _, files) in walkdir(devices_temp)
        for f in files
            endswith(f, ".toml") || continue
            replayed_path = joinpath(dir, f)
            rel = relpath(replayed_path, devices_temp)
            real_path = joinpath(devices_real, rel)
            if !isfile(real_path)
                println("EXTRA  $rel  (replayed but no committed file)")
                fails += 1
                continue
            end
            if is_hand_curated(real_path)
                n_skipped += 1
                continue
            end
            a = TOML.parsefile(real_path)
            b = TOML.parsefile(replayed_path)
            if structural_eq(a, b)
                println("ok     $rel")
                n_compared += 1
            else
                println("DRIFT  $rel")
                fails += 1
            end
        end
    end
    return (compared=n_compared, skipped=n_skipped, fails=fails)
end

# --- Main -------------------------------------------------------------------

function main()
    fail_count = 0
    mktempdir() do tmp
        try
            setup_temp(tmp)
            replay_braket(tmp)
            replay_quantinuum(tmp)
        catch e
            @error "replay failed" exception=(e, catch_backtrace())
            fail_count += 1
        end

        @info "diffing replayed TOMLs against committed devices/"
        result = compare_devices(tmp)
        fail_count += result.fails
        println()
        println("$(result.compared) ok, $(result.fails) drift, $(result.skipped) skipped (hand-curated)")
    end
    exit(fail_count == 0 ? 0 : 1)
end

main()
